INSERT INTO pays VALUES (1, 'Afghanistan');
INSERT INTO pays VALUES (2, 'Afrique du sud');
INSERT INTO pays VALUES (3, 'Albanie');
INSERT INTO pays VALUES (4, 'Algérie');
INSERT INTO pays VALUES (5, 'Allemagne');
INSERT INTO pays VALUES (6, 'Andorre');
INSERT INTO pays VALUES (7, 'Angola');
INSERT INTO pays VALUES (8, 'Antigua-et-Barbuda');
INSERT INTO pays VALUES (9, 'Arabie saoudite');
INSERT INTO pays VALUES (10, 'Argentine');
INSERT INTO pays VALUES (11, 'Arménie');
INSERT INTO pays VALUES (12, 'Australie');
INSERT INTO pays VALUES (13, 'Autriche');
INSERT INTO pays VALUES (14, 'Azerbaïdjan');
INSERT INTO pays VALUES (15, 'Bahamas');
INSERT INTO pays VALUES (16, 'Bahreïn');
INSERT INTO pays VALUES (17, 'Bangladesh');
INSERT INTO pays VALUES (18, 'Barbade');
INSERT INTO pays VALUES (19, 'Belgique');
INSERT INTO pays VALUES (20, 'Belize');
INSERT INTO pays VALUES (21, 'Bénin');
INSERT INTO pays VALUES (22, 'Bhoutan');
INSERT INTO pays VALUES (23, 'Biélorussie');
INSERT INTO pays VALUES (24, 'Birmanie');
INSERT INTO pays VALUES (25, 'Bolivie');
INSERT INTO pays VALUES (26, 'Bosnie-Herzégovine');
INSERT INTO pays VALUES (27, 'Botswana');
INSERT INTO pays VALUES (28, 'Brésil');
INSERT INTO pays VALUES (29, 'Brunei');
INSERT INTO pays VALUES (30, 'Bulgarie');
INSERT INTO pays VALUES (31, 'Burkina Faso');
INSERT INTO pays VALUES (32, 'Burundi');
INSERT INTO pays VALUES (33, 'Cambodge');
INSERT INTO pays VALUES (34, 'Cameroun');
INSERT INTO pays VALUES (35, 'Canada');
INSERT INTO pays VALUES (36, 'Cap-Vert');
INSERT INTO pays VALUES (37, 'Centrafrique');
INSERT INTO pays VALUES (38, 'Chili');
INSERT INTO pays VALUES (39, 'Chine');
INSERT INTO pays VALUES (40, 'Chypre');
INSERT INTO pays VALUES (41, 'Colombie');
INSERT INTO pays VALUES (42, 'Comores');
INSERT INTO pays VALUES (43, 'Congo');
INSERT INTO pays VALUES (44, 'République démocratique du Congo');
INSERT INTO pays VALUES (45, 'Cook Islands');
INSERT INTO pays VALUES (46, 'Corée du Nord');
INSERT INTO pays VALUES (47, 'Corée du Sud');
INSERT INTO pays VALUES (48, 'Costa Rica');
INSERT INTO pays VALUES (49, 'Côte d''Ivoire');
INSERT INTO pays VALUES (50, 'Croatie');
INSERT INTO pays VALUES (51, 'Cuba');
INSERT INTO pays VALUES (52, 'Danemark');
INSERT INTO pays VALUES (53, 'Djibouti');
INSERT INTO pays VALUES (54, 'Dominique');
INSERT INTO pays VALUES (55, 'Égypte');
INSERT INTO pays VALUES (56, 'Équateur');
INSERT INTO pays VALUES (57, 'Érythrée');
INSERT INTO pays VALUES (58, 'Espagne');
INSERT INTO pays VALUES (59, 'Estonie');
INSERT INTO pays VALUES (60, 'États-Unis');
INSERT INTO pays VALUES (61, 'Éthiopie');
INSERT INTO pays VALUES (62, 'Fidji Islands');
INSERT INTO pays VALUES (63, 'Finlande');
INSERT INTO pays VALUES (64, 'France');
INSERT INTO pays VALUES (65, 'Gabon');
INSERT INTO pays VALUES (66, 'Gambie');
INSERT INTO pays VALUES (67, 'Géorgie');
INSERT INTO pays VALUES (68, 'Ghana');
INSERT INTO pays VALUES (69, 'Grèce');
INSERT INTO pays VALUES (70, 'Grenade');
INSERT INTO pays VALUES (71, 'Guatemala');
INSERT INTO pays VALUES (72, 'Guinée');
INSERT INTO pays VALUES (73, 'Guinée-Bissau');
INSERT INTO pays VALUES (74, 'Guinée équatoriale');
INSERT INTO pays VALUES (75, 'Guyana');
INSERT INTO pays VALUES (76, 'Haïti');
INSERT INTO pays VALUES (77, 'Honduras');
INSERT INTO pays VALUES (78, 'Hongrie');
INSERT INTO pays VALUES (79, 'Inde');
INSERT INTO pays VALUES (80, 'Indonésie');
INSERT INTO pays VALUES (81, 'Irak');
INSERT INTO pays VALUES (82, 'Iran');
INSERT INTO pays VALUES (83, 'Irlande');
INSERT INTO pays VALUES (84, 'Islande');
INSERT INTO pays VALUES (85, 'Israël');
INSERT INTO pays VALUES (86, 'Italie');
INSERT INTO pays VALUES (87, 'Jamaïque');
INSERT INTO pays VALUES (88, 'Japon');
INSERT INTO pays VALUES (89, 'Jordanie');
INSERT INTO pays VALUES (90, 'Kazakhstan');
INSERT INTO pays VALUES (91, 'Kenya');
INSERT INTO pays VALUES (92, 'Kirghizistan');
INSERT INTO pays VALUES (93, 'Kiribati');
INSERT INTO pays VALUES (94, 'Koweït');
INSERT INTO pays VALUES (95, 'Laos');
INSERT INTO pays VALUES (96, 'Lesotho');
INSERT INTO pays VALUES (97, 'Lettonie');
INSERT INTO pays VALUES (98, 'Liban');
INSERT INTO pays VALUES (99, 'Libéria');
INSERT INTO pays VALUES (100, 'Libye');
INSERT INTO pays VALUES (101, 'Liechtenstein');
INSERT INTO pays VALUES (102, 'Lituanie');
INSERT INTO pays VALUES (103, 'Luxembourg');
INSERT INTO pays VALUES (104, 'Macédoine');
INSERT INTO pays VALUES (105, 'Madagascar');
INSERT INTO pays VALUES (106, 'Malaisie');
INSERT INTO pays VALUES (107, 'Malawi');
INSERT INTO pays VALUES (108, 'Maldives');
INSERT INTO pays VALUES (109, 'Mali');
INSERT INTO pays VALUES (110, 'Malte');
INSERT INTO pays VALUES (111, 'Maroc');
INSERT INTO pays VALUES (112, 'Marshall Islands');
INSERT INTO pays VALUES (113, 'Maurice');
INSERT INTO pays VALUES (114, 'Mauritanie');
INSERT INTO pays VALUES (115, 'Mexique');
INSERT INTO pays VALUES (116, 'Micronésie');
INSERT INTO pays VALUES (117, 'Moldavie');
INSERT INTO pays VALUES (118, 'Monaco');
INSERT INTO pays VALUES (119, 'Mongolie');
INSERT INTO pays VALUES (120, 'Montenegro');
INSERT INTO pays VALUES (121, 'Mozambique');
INSERT INTO pays VALUES (122, 'Namibie');
INSERT INTO pays VALUES (123, 'Nauru');
INSERT INTO pays VALUES (124, 'Népal');
INSERT INTO pays VALUES (125, 'Nicaragua');
INSERT INTO pays VALUES (126, 'Niger');
INSERT INTO pays VALUES (127, 'Nigéria');
INSERT INTO pays VALUES (128, 'Niue');
INSERT INTO pays VALUES (129, 'Norvège');
INSERT INTO pays VALUES (130, 'Nouvelle-Zélande');
INSERT INTO pays VALUES (131, 'Oman');
INSERT INTO pays VALUES (132, 'Ouganda');
INSERT INTO pays VALUES (133, 'Ouzbékistan');
INSERT INTO pays VALUES (134, 'Palaos');
INSERT INTO pays VALUES (135, 'Palestine');
INSERT INTO pays VALUES (136, 'Panama');
INSERT INTO pays VALUES (137, 'Papouasie-Nouvelle-Guinée');
INSERT INTO pays VALUES (138, 'Paraguay');
INSERT INTO pays VALUES (139, 'Pays-Bas');
INSERT INTO pays VALUES (140, 'Pérou');
INSERT INTO pays VALUES (141, 'Philippines');
INSERT INTO pays VALUES (142, 'Pologne');
INSERT INTO pays VALUES (143, 'Portugal');
INSERT INTO pays VALUES (144, 'Qatar');
INSERT INTO pays VALUES (145, 'Roumanie');
INSERT INTO pays VALUES (146, 'Royaume-Uni');
INSERT INTO pays VALUES (147, 'Russie');
INSERT INTO pays VALUES (148, 'Rwanda');
INSERT INTO pays VALUES (149, 'Saint-Christophe-et-Niévès');
INSERT INTO pays VALUES (150, 'Sainte-Lucie');
INSERT INTO pays VALUES (151, 'Saint-Marin');
INSERT INTO pays VALUES (152, 'Saint-Vincent-et-les-Grenadines');
INSERT INTO pays VALUES (153, 'Salomon Islands');
INSERT INTO pays VALUES (154, 'Salvador');
INSERT INTO pays VALUES (155, 'Samoa Islands');
INSERT INTO pays VALUES (156, 'Sao Tomé-et-Principe');
INSERT INTO pays VALUES (157, 'Sénégal');
INSERT INTO pays VALUES (158, 'Serbie');
INSERT INTO pays VALUES (159, 'Seychelles');
INSERT INTO pays VALUES (160, 'Sierra Leone');
INSERT INTO pays VALUES (161, 'Singapour');
INSERT INTO pays VALUES (162, 'Slovaquie');
INSERT INTO pays VALUES (163, 'Slovénie');
INSERT INTO pays VALUES (164, 'Somalie');
INSERT INTO pays VALUES (165, 'Soudan');
INSERT INTO pays VALUES (166, 'Soudan du sud');
INSERT INTO pays VALUES (167, 'Sri Lanka');
INSERT INTO pays VALUES (168, 'Suède');
INSERT INTO pays VALUES (169, 'Suisse');
INSERT INTO pays VALUES (170, 'Suriname');
INSERT INTO pays VALUES (171, 'Swaziland');
INSERT INTO pays VALUES (172, 'Syrie');
INSERT INTO pays VALUES (173, 'Tadjikistan');
INSERT INTO pays VALUES (174, 'Tanzanie');
INSERT INTO pays VALUES (175, 'Tchad');
INSERT INTO pays VALUES (176, 'République tchèque');
INSERT INTO pays VALUES (177, 'Thaïlande');
INSERT INTO pays VALUES (178, 'Timor oriental');
INSERT INTO pays VALUES (179, 'Togo');
INSERT INTO pays VALUES (180, 'Tonga');
INSERT INTO pays VALUES (181, 'Trinité-et-Tobago');
INSERT INTO pays VALUES (182, 'Tunisie');
INSERT INTO pays VALUES (183, 'Turkménistan');
INSERT INTO pays VALUES (184, 'Turquie');
INSERT INTO pays VALUES (185, 'Tuvalu');
INSERT INTO pays VALUES (186, 'Ukraine');
INSERT INTO pays VALUES (187, 'Uruguay');
INSERT INTO pays VALUES (188, 'Vanuatu');
INSERT INTO pays VALUES (189, 'Vatican');
INSERT INTO pays VALUES (190, 'Venezuela');
INSERT INTO pays VALUES (191, 'Viêt Nam');
INSERT INTO pays VALUES (192, 'Yémen');
INSERT INTO pays VALUES (193, 'Zambie');
INSERT INTO pays VALUES (194, 'Zimbabwe');
