CREATE TABLE World_Stats.Pays
(ID_PAYS INTEGER,
PAYS VARCHAR(50));

INSERT INTO World_Stats.Pays VALUES (1, 'Afghanistan');
INSERT INTO World_Stats.Pays VALUES (2, 'Afrique du sud');
INSERT INTO World_Stats.Pays VALUES (3, 'Albanie');
INSERT INTO World_Stats.Pays VALUES (4, 'Algérie');
INSERT INTO World_Stats.Pays VALUES (5, 'Allemagne');
INSERT INTO World_Stats.Pays VALUES (6, 'Andorre');
INSERT INTO World_Stats.Pays VALUES (7, 'Angola');
INSERT INTO World_Stats.Pays VALUES (8, 'Antigua-et-Barbuda');
INSERT INTO World_Stats.Pays VALUES (9, 'Arabie saoudite');
INSERT INTO World_Stats.Pays VALUES (10, 'Argentine');
INSERT INTO World_Stats.Pays VALUES (11, 'Arménie');
INSERT INTO World_Stats.Pays VALUES (12, 'Australie');
INSERT INTO World_Stats.Pays VALUES (13, 'Autriche');
INSERT INTO World_Stats.Pays VALUES (14, 'Azerbaïdjan');
INSERT INTO World_Stats.Pays VALUES (15, 'Bahamas');
INSERT INTO World_Stats.Pays VALUES (16, 'Bahreïn');
INSERT INTO World_Stats.Pays VALUES (17, 'Bangladesh');
INSERT INTO World_Stats.Pays VALUES (18, 'Barbade');
INSERT INTO World_Stats.Pays VALUES (19, 'Belgique');
INSERT INTO World_Stats.Pays VALUES (20, 'Belize');
INSERT INTO World_Stats.Pays VALUES (21, 'Bénin');
INSERT INTO World_Stats.Pays VALUES (22, 'Bhoutan');
INSERT INTO World_Stats.Pays VALUES (23, 'Biélorussie');
INSERT INTO World_Stats.Pays VALUES (24, 'Birmanie');
INSERT INTO World_Stats.Pays VALUES (25, 'Bolivie');
INSERT INTO World_Stats.Pays VALUES (26, 'Bosnie-Herzégovine');
INSERT INTO World_Stats.Pays VALUES (27, 'Botswana');
INSERT INTO World_Stats.Pays VALUES (28, 'Brésil');
INSERT INTO World_Stats.Pays VALUES (29, 'Brunei');
INSERT INTO World_Stats.Pays VALUES (30, 'Bulgarie');
INSERT INTO World_Stats.Pays VALUES (31, 'Burkina Faso');
INSERT INTO World_Stats.Pays VALUES (32, 'Burundi');
INSERT INTO World_Stats.Pays VALUES (33, 'Cambodge');
INSERT INTO World_Stats.Pays VALUES (34, 'Cameroun');
INSERT INTO World_Stats.Pays VALUES (35, 'Canada');
INSERT INTO World_Stats.Pays VALUES (36, 'Cap-Vert');
INSERT INTO World_Stats.Pays VALUES (37, 'Centrafrique');
INSERT INTO World_Stats.Pays VALUES (38, 'Chili');
INSERT INTO World_Stats.Pays VALUES (39, 'Chine');
INSERT INTO World_Stats.Pays VALUES (40, 'Chypre');
INSERT INTO World_Stats.Pays VALUES (41, 'Colombie');
INSERT INTO World_Stats.Pays VALUES (42, 'Comores');
INSERT INTO World_Stats.Pays VALUES (43, 'Congo');
INSERT INTO World_Stats.Pays VALUES (44, 'République démocratique du Congo');
INSERT INTO World_Stats.Pays VALUES (45, 'Cook Islands');
INSERT INTO World_Stats.Pays VALUES (46, 'Corée du Nord');
INSERT INTO World_Stats.Pays VALUES (47, 'Corée du Sud');
INSERT INTO World_Stats.Pays VALUES (48, 'Costa Rica');
INSERT INTO World_Stats.Pays VALUES (49, 'Côte d''Ivoire');
INSERT INTO World_Stats.Pays VALUES (50, 'Croatie');
INSERT INTO World_Stats.Pays VALUES (51, 'Cuba');
INSERT INTO World_Stats.Pays VALUES (52, 'Danemark');
INSERT INTO World_Stats.Pays VALUES (53, 'Djibouti');
INSERT INTO World_Stats.Pays VALUES (54, 'Dominique');
INSERT INTO World_Stats.Pays VALUES (55, 'Égypte');
INSERT INTO World_Stats.Pays VALUES (56, 'Équateur');
INSERT INTO World_Stats.Pays VALUES (57, 'Érythrée');
INSERT INTO World_Stats.Pays VALUES (58, 'Espagne');
INSERT INTO World_Stats.Pays VALUES (59, 'Estonie');
INSERT INTO World_Stats.Pays VALUES (60, 'États-Unis');
INSERT INTO World_Stats.Pays VALUES (61, 'Éthiopie');
INSERT INTO World_Stats.Pays VALUES (62, 'Fidji Islands');
INSERT INTO World_Stats.Pays VALUES (63, 'Finlande');
INSERT INTO World_Stats.Pays VALUES (64, 'France');
INSERT INTO World_Stats.Pays VALUES (65, 'Gabon');
INSERT INTO World_Stats.Pays VALUES (66, 'Gambie');
INSERT INTO World_Stats.Pays VALUES (67, 'Géorgie');
INSERT INTO World_Stats.Pays VALUES (68, 'Ghana');
INSERT INTO World_Stats.Pays VALUES (69, 'Grèce');
INSERT INTO World_Stats.Pays VALUES (70, 'Grenade');
INSERT INTO World_Stats.Pays VALUES (71, 'Guatemala');
INSERT INTO World_Stats.Pays VALUES (72, 'Guinée');
INSERT INTO World_Stats.Pays VALUES (73, 'Guinée-Bissau');
INSERT INTO World_Stats.Pays VALUES (74, 'Guinée équatoriale');
INSERT INTO World_Stats.Pays VALUES (75, 'Guyana');
INSERT INTO World_Stats.Pays VALUES (76, 'Haïti');
INSERT INTO World_Stats.Pays VALUES (77, 'Honduras');
INSERT INTO World_Stats.Pays VALUES (78, 'Hongrie');
INSERT INTO World_Stats.Pays VALUES (79, 'Inde');
INSERT INTO World_Stats.Pays VALUES (80, 'Indonésie');
INSERT INTO World_Stats.Pays VALUES (81, 'Irak');
INSERT INTO World_Stats.Pays VALUES (82, 'Iran');
INSERT INTO World_Stats.Pays VALUES (83, 'Irlande');
INSERT INTO World_Stats.Pays VALUES (84, 'Islande');
INSERT INTO World_Stats.Pays VALUES (85, 'Israël');
INSERT INTO World_Stats.Pays VALUES (86, 'Italie');
INSERT INTO World_Stats.Pays VALUES (87, 'Jamaïque');
INSERT INTO World_Stats.Pays VALUES (88, 'Japon');
INSERT INTO World_Stats.Pays VALUES (89, 'Jordanie');
INSERT INTO World_Stats.Pays VALUES (90, 'Kazakhstan');
INSERT INTO World_Stats.Pays VALUES (91, 'Kenya');
INSERT INTO World_Stats.Pays VALUES (92, 'Kirghizistan');
INSERT INTO World_Stats.Pays VALUES (93, 'Kiribati');
INSERT INTO World_Stats.Pays VALUES (94, 'Koweït');
INSERT INTO World_Stats.Pays VALUES (95, 'Laos');
INSERT INTO World_Stats.Pays VALUES (96, 'Lesotho');
INSERT INTO World_Stats.Pays VALUES (97, 'Lettonie');
INSERT INTO World_Stats.Pays VALUES (98, 'Liban');
INSERT INTO World_Stats.Pays VALUES (99, 'Libéria');
INSERT INTO World_Stats.Pays VALUES (100, 'Libye');
INSERT INTO World_Stats.Pays VALUES (101, 'Liechtenstein');
INSERT INTO World_Stats.Pays VALUES (102, 'Lituanie');
INSERT INTO World_Stats.Pays VALUES (103, 'Luxembourg');
INSERT INTO World_Stats.Pays VALUES (104, 'Macédoine');
INSERT INTO World_Stats.Pays VALUES (105, 'Madagascar');
INSERT INTO World_Stats.Pays VALUES (106, 'Malaisie');
INSERT INTO World_Stats.Pays VALUES (107, 'Malawi');
INSERT INTO World_Stats.Pays VALUES (108, 'Maldives');
INSERT INTO World_Stats.Pays VALUES (109, 'Mali');
INSERT INTO World_Stats.Pays VALUES (110, 'Malte');
INSERT INTO World_Stats.Pays VALUES (111, 'Maroc');
INSERT INTO World_Stats.Pays VALUES (112, 'Marshall Islands');
INSERT INTO World_Stats.Pays VALUES (113, 'Maurice');
INSERT INTO World_Stats.Pays VALUES (114, 'Mauritanie');
INSERT INTO World_Stats.Pays VALUES (115, 'Mexique');
INSERT INTO World_Stats.Pays VALUES (116, 'Micronésie');
INSERT INTO World_Stats.Pays VALUES (117, 'Moldavie');
INSERT INTO World_Stats.Pays VALUES (118, 'Monaco');
INSERT INTO World_Stats.Pays VALUES (119, 'Mongolie');
INSERT INTO World_Stats.Pays VALUES (120, 'Montenegro');
INSERT INTO World_Stats.Pays VALUES (121, 'Mozambique');
INSERT INTO World_Stats.Pays VALUES (122, 'Namibie');
INSERT INTO World_Stats.Pays VALUES (123, 'Nauru');
INSERT INTO World_Stats.Pays VALUES (124, 'Népal');
INSERT INTO World_Stats.Pays VALUES (125, 'Nicaragua');
INSERT INTO World_Stats.Pays VALUES (126, 'Niger');
INSERT INTO World_Stats.Pays VALUES (127, 'Nigéria');
INSERT INTO World_Stats.Pays VALUES (128, 'Niue');
INSERT INTO World_Stats.Pays VALUES (129, 'Norvège');
INSERT INTO World_Stats.Pays VALUES (130, 'Nouvelle-Zélande');
INSERT INTO World_Stats.Pays VALUES (131, 'Oman');
INSERT INTO World_Stats.Pays VALUES (132, 'Ouganda');
INSERT INTO World_Stats.Pays VALUES (133, 'Ouzbékistan');
INSERT INTO World_Stats.Pays VALUES (134, 'Palaos');
INSERT INTO World_Stats.Pays VALUES (135, 'Palestine');
INSERT INTO World_Stats.Pays VALUES (136, 'Panama');
INSERT INTO World_Stats.Pays VALUES (137, 'Papouasie-Nouvelle-Guinée');
INSERT INTO World_Stats.Pays VALUES (138, 'Paraguay');
INSERT INTO World_Stats.Pays VALUES (139, 'Pays-Bas');
INSERT INTO World_Stats.Pays VALUES (140, 'Pérou');
INSERT INTO World_Stats.Pays VALUES (141, 'Philippines');
INSERT INTO World_Stats.Pays VALUES (142, 'Pologne');
INSERT INTO World_Stats.Pays VALUES (143, 'Portugal');
INSERT INTO World_Stats.Pays VALUES (144, 'Qatar');
INSERT INTO World_Stats.Pays VALUES (145, 'Roumanie');
INSERT INTO World_Stats.Pays VALUES (146, 'Royaume-Uni');
INSERT INTO World_Stats.Pays VALUES (147, 'Russie');
INSERT INTO World_Stats.Pays VALUES (148, 'Rwanda');
INSERT INTO World_Stats.Pays VALUES (149, 'Saint-Christophe-et-Niévès');
INSERT INTO World_Stats.Pays VALUES (150, 'Sainte-Lucie');
INSERT INTO World_Stats.Pays VALUES (151, 'Saint-Marin');
INSERT INTO World_Stats.Pays VALUES (152, 'Saint-Vincent-et-les-Grenadines');
INSERT INTO World_Stats.Pays VALUES (153, 'Salomon Islands');
INSERT INTO World_Stats.Pays VALUES (154, 'Salvador');
INSERT INTO World_Stats.Pays VALUES (155, 'Samoa Islands');
INSERT INTO World_Stats.Pays VALUES (156, 'Sao Tomé-et-Principe');
INSERT INTO World_Stats.Pays VALUES (157, 'Sénégal');
INSERT INTO World_Stats.Pays VALUES (158, 'Serbie');
INSERT INTO World_Stats.Pays VALUES (159, 'Seychelles');
INSERT INTO World_Stats.Pays VALUES (160, 'Sierra Leone');
INSERT INTO World_Stats.Pays VALUES (161, 'Singapour');
INSERT INTO World_Stats.Pays VALUES (162, 'Slovaquie');
INSERT INTO World_Stats.Pays VALUES (163, 'Slovénie');
INSERT INTO World_Stats.Pays VALUES (164, 'Somalie');
INSERT INTO World_Stats.Pays VALUES (165, 'Soudan');
INSERT INTO World_Stats.Pays VALUES (166, 'Soudan du sud');
INSERT INTO World_Stats.Pays VALUES (167, 'Sri Lanka');
INSERT INTO World_Stats.Pays VALUES (168, 'Suède');
INSERT INTO World_Stats.Pays VALUES (169, 'Suisse');
INSERT INTO World_Stats.Pays VALUES (170, 'Suriname');
INSERT INTO World_Stats.Pays VALUES (171, 'Swaziland');
INSERT INTO World_Stats.Pays VALUES (172, 'Syrie');
INSERT INTO World_Stats.Pays VALUES (173, 'Tadjikistan');
INSERT INTO World_Stats.Pays VALUES (174, 'Tanzanie');
INSERT INTO World_Stats.Pays VALUES (175, 'Tchad');
INSERT INTO World_Stats.Pays VALUES (176, 'République tchèque');
INSERT INTO World_Stats.Pays VALUES (177, 'Thaïlande');
INSERT INTO World_Stats.Pays VALUES (178, 'Timor oriental');
INSERT INTO World_Stats.Pays VALUES (179, 'Togo');
INSERT INTO World_Stats.Pays VALUES (180, 'Tonga');
INSERT INTO World_Stats.Pays VALUES (181, 'Trinité-et-Tobago');
INSERT INTO World_Stats.Pays VALUES (182, 'Tunisie');
INSERT INTO World_Stats.Pays VALUES (183, 'Turkménistan');
INSERT INTO World_Stats.Pays VALUES (184, 'Turquie');
INSERT INTO World_Stats.Pays VALUES (185, 'Tuvalu');
INSERT INTO World_Stats.Pays VALUES (186, 'Ukraine');
INSERT INTO World_Stats.Pays VALUES (187, 'Uruguay');
INSERT INTO World_Stats.Pays VALUES (188, 'Vanuatu');
INSERT INTO World_Stats.Pays VALUES (189, 'Vatican');
INSERT INTO World_Stats.Pays VALUES (190, 'Venezuela');
INSERT INTO World_Stats.Pays VALUES (191, 'Viêt Nam');
INSERT INTO World_Stats.Pays VALUES (192, 'Yémen');
INSERT INTO World_Stats.Pays VALUES (193, 'Zambie');
INSERT INTO World_Stats.Pays VALUES (194, 'Zimbabwe');
